### ISSUE TITLE
Missing 'config' ?

### ISSUE THREAD

**Issue by KnowledgeGarden** [madhums/node-express-mongoose#13]
This line of code:
var config = require('config');
exists in several places, e.g. server.js, local.js, express.js and maybe others.
The system will not compile.

On speculation, npm install --save config
just moves errors around.

Curious situation.

**Comment by zsherman** [comment]
Is passing the path into the start command considered good practice? It's making my attempt to use gulp-nodeman extremely difficult.

**Comment by sherwyn** [comment]
heroku config:set NODE_PATH=./config:./app/controllers
heroku config:set NODE_ENV=production

Worked for me.
